config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :line_items
  resources :carts
  resources :order_items

  root to: 'pages#home'
  get '/login', to: "admin/sessions#new"
  get '/logout', to: "admin/sessions#destroy"

  
  

  namespace :admin do
    resources :products do 
      member do 
        get :toggle_status
      end
    end
    resources :dashboards, only: [:index]
    resources :traivans, only: [:index ,:edit, :update]
    resources :sessions, only: [:new ,:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end

    current_item
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity): 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def set_unit_price
      self[:unit_price] = unit_price
    end

    def set_total_price
      self[:total_price] = quantity * set_unit_price
    end


  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

 mount_uploader :image , PhotoUploader
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: { draft: 0, published: 1}

  has_many :order_items , dependent: :destroy
  has_many :photos , dependent: :destroy
  has_many :line_items , dependent: :destroy
  

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: lambda { |attrs|  attrs['image'].blank? }
end

app/models/traivan.rb
class Traivan < ApplicationRecord
  has_secure_password

  validates :fullname, presence: true
  validates :username, format: {with: /@/, message: 'username not valid'}
  validates :password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
  end
  def new
    @cart = Cart.new
  end
  def create
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to carts_url, notice: 'No cart '
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist "
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])

    @line_item = @cart.add_product(product)
    if @line_item.save
      redirect_to @line_item.cart, notice: 'line_item added to cart'
    else
      flash[:alert] = 'There problem to added to cart'
      render :new
    end

  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
    @order_item = OrderItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/traivan_helper.rb
module TraivanHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/font_awsome' %>
  </head>

  <body>
    <%= render 'shared/admin_header_top'%>
    <%= render 'shared/alerts'%>
    <%= render 'shared/admin_second_nav'%>
    
    <div class="container show-products">
      <%= yield %>
    </div>
  
    
    

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <div class="clearfix">
      
    </div>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'shared/alerts'%>
    </div>
    <%= yield %>
  </body>
</html>



   

app/views/pages/home.html.erb
<br>
<main role="main">
  <div class="jumbotron">
    <div class="col-sm-8 mx-auto">
      <h1>Navbar examples</h1>
      <p>This example is a quick exercise to illustrate how the navbar and its contents work. Some navbars extend the width of the viewport, others are confined within a <code>.container</code>. For positioning of navbars, checkout the <a href="../navbar-static/">top</a> and <a href="../navbar-fixed/">fixed top</a> examples.</p>
      <p>At the smallest breakpoint, the collapse plugin is used to hide the links and show a menu button to toggle the collapsed content.</p>
      <p>
        <a class="btn btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
      </p>
    </div>
  </div>
</main>


<section id="list-product">
  <div class="jumbotron">
    <h1>Products For Sale !!!</h1>
    <div class="row">
    <% @products.each do |product|%>
      
        <div class="col-md-3 mt-2">
          <div class="card">
            <div class="card-body">
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. <%= product.title%></p>

              <%= form_for(@order_item) do |f|%>
              <%= f.hidden_field :product_id, value: product.id%>
              <div class="input-group mb-2 mr-sm-2">
                <%= f.text_field :quantity, value: 1, min: 1, class: "form-control"%>
                <div class="input-group-prepend">
                  <%= f.submit 'add to cart', class: "input-group-text" %>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      
    <% end %>
    </div>  
  </div>
</section>

app/views/shared/_admin_footer.html.erb
<div class="row d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-0 bg-white border-bottom shadow-sm" id="footer-botton">
  <div class="col-md-12">
    <div class="float-left"><b>Copyright </b>&copy; 2018</div>
    <div class="float-right">Admin system</div>
  </div>
</div>

app/views/shared/_admin_header_top.html.erb
<div class="header-top-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="logo-area float-left">Traivan</div>
        <div class="float-right logo-area">
          <%= link_to logout_path do %>
            <i class="fas fa-sign-out-alt"> </i> Logout
          <% end %>
        </div>
      </div><!--col-lg-12-->
    </div><!--row-->
  </div><!--container-->
</div><!--header-top-area-->

app/views/shared/_admin_second_nav.html.erb
<div class="head-second-nav">
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to admin_dashboards_path, class: "nav-link #{active? admin_dashboards_path }" do %>
          <i class="fas fa-home"></i> Home
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_traivans_path, class: "nav-link  #{active? admin_traivans_path }" do %>
          <i class="far fa-user"></i> Admin
        <% end %>
      </li>

       <li class="nav-item">
        <%= link_to admin_products_path, class: "nav-link #{active? admin_products_path}" do %>
          <i class="fas fa-tram"></i> Products
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to '#', class: "nav-link " do %>
          <i class="fas fa-cart-arrow-down"></i> Orders
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to '#', class: "nav-link " do %>
          <i class="fas fa-cog"></i> Settings
        <% end %>
      </li>
    </ul>
  </div><!--container-->
</div><!--head-second-nav-->

app/views/shared/_alerts.html.erb
<div class="container">
  <%if flash[:notice]%>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:notice]%>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <%if flash[:alert]%>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= flash[:alert]%>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_column_list_4.html.erb
<div class="column-list-4">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <div class="column-inner bg-white">
            <h2><span class="counter">50,000</span></h2>
            <p>Total Website Traffics</p>
        </div>
      </div><!--col-lg-3-->

      <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <div class="column-inner bg-white">
            <h2><span class="counter">50,000</span></h2>
            <p>Total Website Traffics</p>
        </div>
      </div><!--col-lg-3-->

      <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <div class="column-inner bg-white">
            <h2><span class="counter">50,000</span></h2>
            <p>Total Website Traffics</p>
        </div>
      </div><!--col-lg-3-->

      <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <div class="column-inner bg-white">
            <h2><span class="counter">50,000</span></h2>
            <p>Total Website Traffics</p>
        </div>
      </div><!--col-lg-3-->


    </div><!--row-->
</div><!--column-list-4-->

app/views/shared/_font_awsome.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in?%>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete , class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path,class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>