config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :line_items
  resources :carts
  resources :order_items

  root to: 'pages#home'
  get '/login', to: "admin/sessions#new"
  get '/logout', to: "admin/sessions#destroy"

  
  

  namespace :admin do
    resources :products do 
      member do 
        get :toggle_status
      end
    end
    resources :dashboards, only: [:index]
    resources :traivans, only: [:index ,:edit, :update]
    resources :sessions, only: [:new ,:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end

    current_item
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity): 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def set_unit_price
      self[:unit_price] = unit_price
    end

    def set_total_price
      self[:total_price] = quantity * set_unit_price
    end


  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

 mount_uploader :image , PhotoUploader
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: { draft: 0, published: 1}

  has_many :order_items , dependent: :destroy
  has_many :photos , dependent: :destroy
  has_many :line_items , dependent: :destroy
  

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: lambda { |attrs|  attrs['image'].blank? }
end

app/models/traivan.rb
class Traivan < ApplicationRecord
  has_secure_password

  validates :fullname, presence: true
  validates :username, format: {with: /@/, message: 'username not valid'}
  validates :password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/traivans_controller.rb
class Admin::TraivansController < Admin::ApplicationController
  def index
    @traivans = Traivan.all
  end

  def edit
    @traivan = Traivan.find(params[:id])
  end

  def update
    @traivan = Traivan.find(params[:id])
    if @traivan.update(traivan_params)
      redirect_to admin_traivans_path, notice: 'Admin was success full updated'
    else
      flash[:alert] = 'There was problem updated'
      render :edit
    end 
  end

  private
    def traivan_params
      params.require(:traivan).permit(:fullname, :username, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  include ApplicationHelper #to use session
  include CurrentCart
  before_action :set_cart

 

  def reset_session
    @_request.reset_session
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
  end
  def new
    @cart = Cart.new
  end
  def create
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to carts_url, notice: 'No cart '
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist "
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])

    @line_item = @cart.add_product(product)
    if @line_item.save
      redirect_to @line_item.cart, notice: 'line_item added to cart'
    else
      flash[:alert] = 'There problem to added to cart'
      render :new
    end

  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
    @order_item = OrderItem.new
  end
end

app/helpers/admin/traivans_helper.rb
module Admin::TraivansHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/traivan_helper.rb
module TraivanHelper
end

app/views/admin/traivans/edit.html.erb
<div class="card" style="height:  550px;">
  <div class="card-header">
    <h1 class="text-center">Edit Administrator User</h1>
  </div>
  <div class="card-body">
    <%=  form_for [:admin, @traivan] do |f|%>
      <%if @traivan.errors.any? %>
        <div class="text-warning">
          <h2><%= pluralize(@traivan.errors.count, "error")%> from being edit adminstrator user</h2>
          <ol>
            <% @traivan.errors.full_messages.each do |msg|%>
              <li><%= msg%></li>
            <% end %>
          </ol>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :fullname%>
        <%= f.text_field :fullname, class: "form-control"%>
      
      </div>

      <div class="form-group">
        <%= f.label :username%>
        <%= f.email_field :username, class: "form-control"%>
      </div>

      <div class="form-group">
        <%= f.label :password%>
        <%= f.password_field :password, class: "form-control"%>
      </div>

      <div class="form-group">
        <%= f.submit 'Update Administrator', class: "btn btn-success"%>
      </div>


    <% end %>
  </div>
</div>

app/views/admin/traivans/index.html.erb
<div class="traivan-inner bg-white">
  <h1>Administrator</h1>
  <hr>
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>#</th>
        <th>Fullname</th>
        <th>Username</th>
        <th>Created</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @traivans.each do |traivan|%>
      <tr>
        <td><%= traivan.id%></td>
        <td><%= traivan.fullname%></td>
        <td><%= traivan.username%></td>
        <td><%= time_ago_in_words traivan.created_at%></td>
        <td>
            <%= link_to 'Edit', edit_admin_traivan_path(traivan) , class: "btn btn-danger btn-sm"%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
</div><!--traivan-inner-->

app/views/admin/traivans/update.html.erb
<h1>Admin::Traivans#update</h1>
<p>Find me in app/views/admin/traivans/update.html.erb</p>