config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :line_items
  resources :carts
  resources :order_items

  root to: 'pages#home'
  get '/login', to: "admin/sessions#new"
  get '/logout', to: "admin/sessions#destroy"

  
  

  namespace :admin do
    resources :products do 
      member do 
        get :toggle_status
      end
    end
    resources :dashboards, only: [:index]
    resources :traivans, only: [:index ,:edit, :update]
    resources :sessions, only: [:new ,:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end

    current_item
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity): 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def set_unit_price
      self[:unit_price] = unit_price
    end

    def set_total_price
      self[:total_price] = quantity * set_unit_price
    end


  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

 mount_uploader :image , PhotoUploader
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: { draft: 0, published: 1}

  has_many :order_items , dependent: :destroy
  has_many :photos , dependent: :destroy
  has_many :line_items , dependent: :destroy
  

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: lambda { |attrs|  attrs['image'].blank? }
end

app/models/traivan.rb
class Traivan < ApplicationRecord
  has_secure_password

  validates :fullname, presence: true
  validates :username, format: {with: /@/, message: 'username not valid'}
  validates :password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  
  def index
    @products = Product.all.order(id: :desc).page(params[:page]).per(20)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: 'Product was successful created'
    else
      flash[:alert] = 'Product was problem created'
    end
  end
  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    @product.traivan_id = current_traivan.id

    if @product.update(product_params)
      redirect_to admin_products_path, notice: 'Product was successful updated'
    else
      flash[:alert] = 'Product was problem updated'
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, notice: 'Product was successful delete'
  end

  def toggle_status
    @product = Product.find(params[:id])
    if @product.draft?
      @product.published!
    elsif @product.published?
      @product.draft!
    end

    redirect_to admin_products_url, notice: 'Status was successful updated'
  end

  private
    def product_params
      params.require(:product).permit(:title, :price, :description ,:status, photos_attributes: [:id ,:image , :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  include ApplicationHelper #to use session
  include CurrentCart
  before_action :set_cart

 

  def reset_session
    @_request.reset_session
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
  end
  def new
    @cart = Cart.new
  end
  def create
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to carts_url, notice: 'No cart '
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist "
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])

    @line_item = @cart.add_product(product)
    if @line_item.save
      redirect_to @line_item.cart, notice: 'line_item added to cart'
    else
      flash[:alert] = 'There problem to added to cart'
      render :new
    end

  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
    @order_item = OrderItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/traivan_helper.rb
module TraivanHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin ,@product] do |f|%>
<div class="card-footer">
  <div class="row">
    <div class="col-md-4 card">
      <h2>Add Photos</h2>
      <div>
        <%= f.fields_for :photos do |photo|%>
          <%= render 'photo_fields', f: photo%>
        <% end %>

        <div class="pt-3">
          <%= link_to_add_association 'Add Photo', f, :photos, class: "btn btn-secondary btn-sm"%>
        </div>
      </div>
      
    </div><!--end of col-md-4-->

    <div class="col-md-8">
      <div class="form-group">
          <%= f.label :title%>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :price%>
          <%= f.number_field :price, value: 1,class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :description%>
          <%= f.text_area :description, rows: 5,class: "form-control"%>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim </p>
    </div>
  </div>
</div>

<div class="card-footer">
  <div class="btn-group " role="group" aria-label="Basic example">
    <%= link_to 'CANCEL', admin_products_path, class: "btn btn-outline-secondary"%>
    <%=f.submit 'SAVE PRODUCT', class: "btn btn-outline-secondary"%>
  </div>
</div>
<% end%>

app/views/admin/products/_photo_fields.html.erb
<div class="custom-file nested-fields">
  <div>
    <label class="custom-file-label" for="customFile">Choose file</label>
    <%= f.file_field :image,  class: "custom-file-input" ,id: "customFile"%>
  </div>
  <div class="pt-2">
    <%= link_to_remove_association 'Remove Photo', f , class: "btn btn-secondary btn-sm "%>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Edit Product</h1>
  </div>
    <%= render 'form'%>
</div>

app/views/admin/products/index.html.erb
<div class="traivan-inner bg-white">
  <div class="float-left"><h3>List products</h3></div>
  <div class="float-right"> <%= link_to 'New Product', new_admin_product_path , class: "btn btn-primary btn-sm" %></div>

  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>price</th>
        <th>Status</th>
        <th>created</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product|%>
      <tr>
        <td><%= product.id%></td>
        <td><%= product.title%></td>
        <td><%= number_to_currency product.price%></td>
        <td><%= link_to product.status, toggle_status_admin_product_path(product) %></td>
        <td><%= time_ago_in_words product.created_at%></td>
        <td>
          <%= link_to 'show', admin_product_path(product) , class: "text-success "%>
          <%= link_to 'edit', edit_admin_product_path(product) , class: "text-warning "%>
          <%= link_to 'delete', admin_product_path(product), method: :delete, data: {confirm: 'Are you sure?'} , class: "text-danger "%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @products, theme:  'twitter-bootstrap-4', pagination_class: "pagination-sm"%>

</div>

app/views/admin/products/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Create Product</h4>
  </div>
    <%= render 'form'%>
</div>

app/views/admin/products/show.html.erb
<div class="traivan-inner bg-white">

<h6 class="float-left"><b>Product Name: </b><span class="text-success"><%= @product.title %></span></h6>
<div class="float-right">
  <%= link_to 'back' , admin_products_path , class: "text-success"%>
  <%= link_to 'edit' , edit_admin_product_path(@product.id) , class: "text-warning"%>
  <%= link_to 'delete' , admin_product_path(@product.id) ,method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger"%>
</div>

<div class="clearfix"></div>

<h6><b>Product Price: </b> <span class="text-success"><%= number_to_currency @product.price%></span></h6>
<h6><b>Status:</b>  <span class="text-success"><%= @product.status%></span></h6>
<h6>Photo of products: </h6>
<hr>
<%@product.photos.each do |photo|%>
  <%= image_tag photo.image.url%>
<% end %>
</div>